"""Constants for Device Lifecycle."""

DOMAIN = "device_lifecycle"
CONFIG_ENTRY_VERSION = 4

SUBENTRY_TYPE_PURCHASE = "purchase"
SUBENTRY_TYPE_RUNTIME = "runtime"

# Stable Asset Core references stored inside config subentries. The normalized
# Asset/Purchase objects themselves live in Device Lifecycle storage.
CONF_PURCHASE_UUID = "purchase_uuid"
CONF_ASSET_UUID = "asset_uuid"

CONF_ASSET_NAME = "name"
CONF_CATEGORY = "category"
CONF_MANUFACTURER = "manufacturer"
CONF_MODEL = "model"
CONF_MODEL_ID = "model_id"
CONF_SERIAL_NUMBER = "serial_number"
CONF_SW_VERSION = "sw_version"
CONF_HW_VERSION = "hw_version"

CONF_DEVICE_ID = "device_id"
CONF_DEVICE_IDS = "device_ids"
CONF_PURCHASE_NAME = "purchase_name"
CONF_PURCHASE_DATE = "purchase_date"
CONF_INSTALLED_DATE = "installed_date"
CONF_WARRANTY_TYPE = "warranty_type"
CONF_WARRANTY_UNTIL = "warranty_until"
CONF_SELLER = "seller"
CONF_PURCHASE_PRICE = "purchase_price"
CONF_CURRENCY = "currency"
CONF_RECEIPT_REFERENCE = "receipt_reference"
CONF_RECEIPT_URL = "receipt_url"
CONF_NOTES = "notes"

CONF_DEPLOYMENT_STATE = "deployment_state"
CONF_HA_AREA_ID = "ha_area_id"
CONF_HA_RELATIONSHIP_ACTION = "ha_relationship_action"
CONF_CLEAR_INSTALLED_DATE = "clear_installed_date"
CONF_CLEAR_HA_AREA = "clear_ha_area"
CONF_CONFIRM_AREA_CLEAR = "confirm_area_clear"

CONF_LIFECYCLE_STATUS = "lifecycle_status"
CONF_EFFECTIVE_DATE = "effective_date"
CONF_REPLACEMENT_DIRECTION = "replacement_direction"
CONF_REPLACEMENT_TARGET_ASSET_UUID = "replacement_target_asset_uuid"
CONF_PREDECESSOR_ASSET_UUID = "predecessor_asset_uuid"
CONF_SUCCESSOR_ASSET_UUID = "successor_asset_uuid"
CONF_REPLACEMENT_REASON = "replacement_reason"
CONF_REPLACEMENT_UUID = "replacement_uuid"
CONF_REPLACEMENT_ACTION = "replacement_action"
CONF_VOID_REASON = "void_reason"
CONF_CONFIRM_DISPOSED = "confirm_disposed"
CONF_CONFIRM_VOID = "confirm_void"

CONF_RUNTIME_MODE = "runtime_mode"
CONF_RUNTIME_DATA_VERSION = "runtime_data_version"
CONF_SOURCE_ENTITY_ID = "source_entity_id"
CONF_POWER_THRESHOLD = "power_threshold"
CONF_POWER_HYSTERESIS = "power_hysteresis"

WARRANTY_NONE = "none"
WARRANTY_ONE_YEAR = "1_year"
WARRANTY_TWO_YEARS = "2_years"
WARRANTY_MANUAL = "manual"

WARRANTY_TYPES = (
    WARRANTY_NONE,
    WARRANTY_ONE_YEAR,
    WARRANTY_TWO_YEARS,
    WARRANTY_MANUAL,
)

RUNTIME_MODE_ON = "on_state"
RUNTIME_MODE_POWER = "power"

RUNTIME_MODES = (
    RUNTIME_MODE_ON,
    RUNTIME_MODE_POWER,
)

DEFAULT_POWER_THRESHOLD = 1.0
DEFAULT_POWER_HYSTERESIS = 0.0
RUNTIME_DATA_VERSION = 1

DEPLOYMENT_STATE_UNKNOWN = "unknown"
DEPLOYMENT_STATE_NOT_DEPLOYED = "not_deployed"
DEPLOYMENT_STATE_DEPLOYED = "deployed"

DEPLOYMENT_STATES = (
    DEPLOYMENT_STATE_UNKNOWN,
    DEPLOYMENT_STATE_NOT_DEPLOYED,
    DEPLOYMENT_STATE_DEPLOYED,
)

LIFECYCLE_STATUS_UNKNOWN = "unknown"
LIFECYCLE_STATUS_ACTIVE = "active"
LIFECYCLE_STATUS_RETIRED = "retired"
LIFECYCLE_STATUS_DISPOSED = "disposed"
LIFECYCLE_STATUS_LOST = "lost"

LIFECYCLE_STATUSES = (
    LIFECYCLE_STATUS_UNKNOWN,
    LIFECYCLE_STATUS_ACTIVE,
    LIFECYCLE_STATUS_RETIRED,
    LIFECYCLE_STATUS_DISPOSED,
    LIFECYCLE_STATUS_LOST,
)

REPLACEMENT_REASON_UNKNOWN = "unknown"
REPLACEMENT_REASON_PLANNED_REFRESH = "planned_refresh"
REPLACEMENT_REASON_UPGRADE = "upgrade"
REPLACEMENT_REASON_FAILURE = "failure"
REPLACEMENT_REASON_WARRANTY_RMA = "warranty_rma"
REPLACEMENT_REASON_OTHER = "other"

REPLACEMENT_REASONS = (
    REPLACEMENT_REASON_UNKNOWN,
    REPLACEMENT_REASON_PLANNED_REFRESH,
    REPLACEMENT_REASON_UPGRADE,
    REPLACEMENT_REASON_FAILURE,
    REPLACEMENT_REASON_WARRANTY_RMA,
    REPLACEMENT_REASON_OTHER,
)

REPLACEMENT_DIRECTION_PREDECESSOR = "predecessor"
REPLACEMENT_DIRECTION_SUCCESSOR = "successor"
REPLACEMENT_DIRECTIONS = (
    REPLACEMENT_DIRECTION_PREDECESSOR,
    REPLACEMENT_DIRECTION_SUCCESSOR,
)

REPLACEMENT_ACTION_CORRECT = "correct"
REPLACEMENT_ACTION_VOID = "void"
REPLACEMENT_ACTIONS = (
    REPLACEMENT_ACTION_CORRECT,
    REPLACEMENT_ACTION_VOID,
)

HA_RELATIONSHIP_ACTION_REPLACE = "replace"
HA_RELATIONSHIP_ACTION_UNLINK = "unlink"
HA_RELATIONSHIP_ACTIONS = (
    HA_RELATIONSHIP_ACTION_REPLACE,
    HA_RELATIONSHIP_ACTION_UNLINK,
)
